site_name: RoR Interface & Addon Docs
site_url: https://<your-user>.github.io/RoR-Interface
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
plugins:
  - search
  - table-reader
nav:
  - Home: index.md
  - Interface Browser:
      - Latest: interface/latest/index.md
repo_url: https://github.com/xyeppp/RoR-Interface
